### ISSUE TITLE
Cannot load LogbackConfigListener on JDK 6

### ISSUE THREAD

**Issue by ghost** [qos-ch/logback-extensions#25]
I'm having the following issue with logback-ext-spring-0.1.2.jar on JDK 6

\# java -version
java version "1.6.0_27"
OpenJDK Runtime Environment (IcedTea6 1.12.6) (6b27-1.12.6-1ubuntu0.10.04.2)
OpenJDK 64-Bit Server VM (build 20.0-b12, mixed mode)

Stacktrace:

java.lang.UnsupportedClassVersionError: ch/qos/logback/ext/spring/web/LogbackConfigListener : Unsupported major.minor version 51.0 (unable to load class ch.qos.logback.ext.spring.web.LogbackConfigListener)

Can you support JDK 6 by updating maven-compiler-plugin plugin in pom.xml to support JDK 6? Something like
            \<source\>1.6\</source\>
            \<target\>1.6\</target\>

**Comment by oysteinhagenpettersen** [comment]
Any plans to support java 6?

Thanks.

**Comment by mikereinhold** [comment]
The Logback team polled the dev and user community a while back asking
about migrating the project to a newer Java specification in order to be
able to take advantage of new language features at the cost of
compatibility. At that point in time, there was little to no pushback from
the community because Oracle has had Java 5 & 6 in an End of Support state
for quite a while.

Depending on what newer language features have been used by commits merged
into the project since that time, just changing the JDK version in the pom
will most likely break the build.

Is there a particular reason your project is stuck on JDK 5 or 6 so you can
use the most recent versions? If you absolutely need JDK 5 or 6, you'll
have to use an older version of Logback that was built prior to the change
(not sure which version had that off the top of my head, but you can find
it in the release notes I'm sure).

Regards,
Mike

On Thu, Feb 5, 2015 at 9:44 AM, oysteinhagenpettersen <
notifications@github.com> wrote:

> Any plans to support java 6?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qos-ch/logback-extensions/issues/25#issuecomment-73056862>
> .
>



-- 
*Mike Reinhold* | Co-Founder

**Comment by oysteinhagenpettersen** [comment]
Thanks for you comment. Cannot move away from Java6 at the moment. Will review the release notes and use an older version. 

Regs
Oystein

**Comment by tony19** [comment]
@magixsource, to rebuild logback-extensions with a different JDK version, specify `jdk.version=<version>` from the command line. For example, to specify 1.6:

```bash
mvn clean package -Djdk.version=1.6
```

**Comment by tony19** [comment]
@mikereinhold, the poll you mention was specific to logback proper IIRC. It seems logback-extensions should at least match the JDK versions that logback supports to maintain compatibility. And that's a trivial change with minimal impact.
